### ISSUE TITLE
Expected 'Assertion', got 'Response'

### ISSUE THREAD

**Issue by andyboeh** [ck-ws/pam-script-saml#1]
Hey,
I just discovered pam-script-saml and tried to set it up. For me, it always gives the following error: 

`Anerror occured while parsing the Assertion: Expected 'Assertion' xml node and 'urn:oasis:names:tc:SAML:2.0:assertion' namespace but got node 'Response' and namespace 'urn:oasis:names:tc:SAML:2.0:protocol'`
I had to change the deserializer to first parse the response and then extract the assertion with getFirstAssertion().

I'm using simplesamlphp as idp.

**Comment by ck-ws** [comment]
Hi Andy,
sorry for the late response.

It seems it depends much on the application which part of the response is really returned. So the IdP is not that relevant (I'm using SimpleSAMLphp, too), but it would be more interesting what you are using as SP. In my case it's a SOGo installation which itself uses liblasso for the SP implementation.

If you see a solution to check which node is really given (is it only the assertion or a full response) and can process the payload based on it I would be happy to accept a PR for this :)

**Comment by andyboeh** [comment]
Thanks, for the clarification, I wasn't really aware of the difference between Response and Assertion.
My SP is mod_auth_mellon, since I was too lazy to write a SAML plugin for Roundcube Webmail. I configured it with the directive `MellonDumpResponse On` and adapted Roundcube's http_authentication plugin to use the SAML Reponse as password.

**Comment by ck-ws** [comment]
As you have written above, the assertion is wrapped in a response. It looks like this case is handled differently between implementations.

Btw, that's a neat solution. I was looking into sth like that with RainLoop webmail, but using the Shibboleth SP. It can't dump the response, but there is a way to access it, when configured correctly: https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAssertionExport
And it looks like it only exports the assertion, too.
